# TODO: Install the following libraries
# pip install diffusers==0.33.1
# pip install streamlit==1.45.0

# to run the code, use the command:
# streamlit run 4_image_geneation_exercise.py

# app.py
import streamlit as st
from diffusers import StableDiffusionPipeline
import torch

@st.cache_resource(show_spinner=False)
def load_pipeline(model_name: str = "runwayml/stable-diffusion-v1-5"):
    """Load and cache the Stable Diffusion pipeline."""
    pipe = StableDiffusionPipeline.from_pretrained(
        model_name, torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
    )
    if torch.cuda.is_available():
        pipe = pipe.to("cuda")
    return pipe

def main():
    st.set_page_config(page_title="Stable Diffusion Explorer", layout="wide")
    st.title("🎨 Stable Diffusion Art Generator")

    # Sidebar for settings
    st.sidebar.header("Generation Settings")
    prompt = st.sidebar.text_area("Enter your text prompt", value="A serene landscape at sunrise")
    style = st.sidebar.selectbox("Select an art style", [
        "Digital art, high detail",
        "Watercolor painting",
        "Cyberpunk neon",
        "Vintage oil painting",
        "Pixel art"
    ])
    steps = st.sidebar.slider("Inference steps", 10, 100, 50)
    guidance = st.sidebar.slider("Guidance scale", 1.0, 20.0, 7.5)

    if st.sidebar.button("Generate"):
        full_prompt = f"{prompt}, {style}"
        st.subheader("Prompt")
        st.write(full_prompt)

        with st.spinner("Generating image..."):
            pipe = load_pipeline()
            image = pipe(
                full_prompt,
                num_inference_steps=steps,
                guidance_scale=guidance
            ).images[0]

        st.image(image, caption="Generated by Stable Diffusion", use_column_width=True)

if __name__ == "__main__":
    main()
